### ISSUE TITLE
Issues with `mp_api`

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_atomistics#1054]
Currently the unit tests fail with the following error message: 
```
======================================================================
ERROR: vasp.test_vasprun (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: vasp.test_vasprun
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/my-env/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/share/miniconda3/envs/my-env/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/pyiron_atomistics/pyiron_atomistics/tests/vasp/test_vasprun.py", line 9, in <module>
    from pyiron_atomistics.vasp.vasprun import Vasprun, VasprunError
  File "/home/runner/work/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/vasp/vasprun.py", line 13, in <module>
    from pyiron_atomistics.dft.waves.electronic import ElectronicStructure
  File "/home/runner/work/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/__init__.py", line 4, in <module>
    from pyiron_atomistics.project import Project
  File "/home/runner/work/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/project.py", line 34, in <module>
    from pyiron_atomistics.atomistics.structure.factory import StructureFactory
  File "/home/runner/work/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/atomistics/structure/factory.py", line 39, in <module>
    from pyiron_atomistics.atomistics.structure.factories.materialsproject import (
  File "/home/runner/work/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/atomistics/structure/factories/materialsproject.py", line 2, in <module>
    from mp_api.client import MPRester
  File "/usr/share/miniconda3/envs/my-env/lib/python3.8/site-packages/mp_api/client/__init__.py", line 6, in <module>
    from .mprester import MPRester
  File "/usr/share/miniconda3/envs/my-env/lib/python3.8/site-packages/mp_api/client/mprester.py", line 26, in <module>
    from mp_api.client.routes import (
  File "/usr/share/miniconda3/envs/my-env/lib/python3.8/site-packages/mp_api/client/routes/__init__.py", line 3, in <module>
    from ._general_store import GeneralStoreRester
  File "/usr/share/miniconda3/envs/my-env/lib/python3.8/site-packages/mp_api/client/routes/_general_store.py", line 3, in <module>
    from emmet.core._general_store import GeneralStoreDoc
  File "/usr/share/miniconda3/envs/my-env/lib/python3.8/site-packages/emmet/core/_general_store.py", line 11, in <module>
    class GeneralStoreDoc(BaseModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/share/miniconda3/envs/my-env/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

**Comment by jan-janssen** [comment]
I reported the issue up-stream https://github.com/materialsproject/emmet/issues/740
