### ISSUE TITLE
Custom Vasp-Job fails on Cluster

### ISSUE THREAD

**Issue by fldei101** [pyiron/pyiron_atomistics#1058]
**Summary**

In one of our hackathon we developed a class which inherits from the Vasp class in order to modify the writing of the input, collecting the output etc. to create additional input files.

```
from pyiron_base import state, Executable
from pyiron_atomistics.vasp.vasp import Vasp

class VaspTIPsol(Vasp):
    
    def _executable_activate(self, enforce=False):
        """
        Internal helper function to load the executable object, if it was not loaded already.
        """
        if self._executable is None or enforce:
            self._executable = Executable(
                codename="vasp",
                module="vasp",
                path_binary_codes=state.settings.resource_paths,
            )
            
    def collect_output(self):
        import os
        import shutil
        dir_path = self.working_directory + "/__pycache__"
        # checking whether file exists or not
        try:
            shutil.rmtree(dir_path)
        except OSError as e:
            pass
        
        super().collect_output()
    
    
    def write_input(self):
        super().write_input()
        # do some logic
```

This approach works fine on the head node, but fails if we want to assign multiple cores and submit it on the cluster, for example:

```
job.server.queue = "cm"
job.server.cores = 4
```
leads to the following crash:

**Actual Behavior**
```
Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/cli/__main__.py", line 3, in <module>
    main()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/cli/control.py", line 59, in main
    args.cli(args)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/cli/wrapper.py", line 31, in main
    job_wrapper_function(
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/jobs/job/wrapper.py", line 148, in job_wrapper_function
    job = JobWrapper(
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/jobs/job/wrapper.py", line 61, in __init__
    self.job = pr.load(int(job_id))
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/project/generic.py", line 850, in load
    return self.load_from_jobpath(
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/project/generic.py", line 873, in load_from_jobpath
    job = job.to_object()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/jobs/job/core.py", line 500, in to_object
    return self.project_hdf5.to_object(object_type, **qwargs)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/storage/hdfio.py", line 1385, in to_object
    class_object = self.import_class(class_name)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/storage/hdfio.py", line 1324, in import_class
    return getattr(
AttributeError: module '__main__' has no attribute 'VaspTIPsol'
```
Is it possible to fix this error with the custom class? I already tried to copy the VaspTIPsol.py file into the working directory with no success.

Thanks for your help!

**Comment by niklassiemer** [comment]
You have to make sure pyiron knows how to get your custom class. Background: pyiron if submitted  will spawn an entirely new python interpreter, in which your class is not available. You may e.g. send the full notebook with your class defined within to the cluster.
Otherwise you can add your class to the JOB_CLASS_DICT  of a local copy of pyiron and use this local copy via the PYTHONPATH of your .bashrc.

**Comment by fldei101** [comment]
Hi Niklas, 

thanks for your answer. How would I do this 'You may e.g. send the full notebook with your class defined within to the cluster.'? Because I thought it is already enough to have the class in the working directory?
I do not want to modify the .pyiron file / PYTHONPATH because it makes it way more difficult to have a MWE since it would not run in the default environment.

**Comment by pmrv** [comment]
It's possible to submit a whole notebook with the `ScriptJob`.  If you define the class inside the notebook it should work.  Basically you'd have to 

1. create the script job and set its run_mode to queue
2. inside the notebook you're submitting run the the modified vasp job without setting the run_mode (we call that 'modal')

**Comment by pmrv** [comment]
Iirc this issue was resolved in person.  As written job classes need to be importable to be submitted to job classes, which generally means defining them in a separate, findable source file.  Alternatively a whole notebook can be submitted with `ScriptJob`.
