### ISSUE TITLE
lammps job with other executable crashes

### ISSUE THREAD

**Issue by fldei101** [pyiron/pyiron_atomistics#150]
**Summary**
Dear all,

I have a problem running my own lammps executable on the hpc with pyiron. I was not sure where to post it, hopefully it is fine here. I try to adapt one of the sh files in the bin folder to run pyiron jobs with my own executable (I need this because I included a new fix). When I try to run the job it crashes immediately. I use the same submission command for lammps jobs without pyiron and there it works.
(I also tried to submit it with mpiexec but it is still crashing, if necessary I can post the backtrace)

Maybe someone can confirm this or tell me what is going wrong?

Thanks in advance!

**pyiron Version and Platform**

pyiron - 0.4.3

**Expected Behavior**
It works.

**Actual Behavior**
The job fails.

**Steps to Reproduce**
I copied one of the sh files inside the bin folder, loaded the module and adapted the submission command:
```
#!/bin/bash
module load pyiron/dev
module load lammps/3Mar20
srun -n $1 lmp_serial.cmfe -in control.inp
```
When the jobs starts, it crashes immediately and the error.msg says:
```
srun: error: Invalid numeric value "lmp_serial.cmfe" for --ntasks.
```
and I find in the error.out:
```
Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py", line 724, in run_static
    universal_newlines=True,
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/u/deissei/pyiron-resources-cmmc/lammps/bin/run_lammps_2021_flo.sh' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/cli/__main__.py", line 2, in <module>
    main()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/cli/__init__.py", line 61, in main
    args.cli(args)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/cli/wrapper.py", line 39, in main
    submit_on_remote=args.submit
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/wrapper.py", line 149, in job_wrapper_function
    job.run()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/wrapper.py", line 115, in run
    self.job.run_static()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py", line 757, in run_static
    raise RuntimeError("Job aborted")
RuntimeError: Job aborted
```
I checked if this could be a problem of the run_queue.sh but ntasks equals one as it should.

**Further Information, Files, and Links**

**Comment by max-hassani** [comment]
I think you should add the path to your executable in your `.pyiron` file within your home directory. Have you done that?
An instruction for that is given [here](https://pyiron.readthedocs.io/en/latest/source/installation.html#use-your-own-executable-for-lammps-s-phi-nx-or-gpaw)

**Comment by fldei101** [comment]
If I understand correctly this is what I have done. I copied the cmmc-resources folder to my directory, changed the path in the ```.pyiron``` file. Then I did the changes I described in my issue report. And finally I restarted my jupyter.
```module load lammps/3Mar20``` should add the executable similar to the vasp executables.

**Comment by niklassiemer** [comment]
Hi,
what is the name of the shell script in you bin folder? Does it contain the `mpi` flag? If not, pyiron assumes a serial computation and does not pass additional command line arguments while you expect the number of cores in `$1`.

**Comment by niklassiemer** [comment]
Actually, why do you start the `serial` version with more than one core?

**Comment by fldei101** [comment]
Perfect, this was the issue. I thought it is mandatory to write ```$1``` in the submission script.
