### ISSUE TITLE
Notebook tests with interactive lammps calculation fail

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_atomistics#216]
Based on #214 and #215 it seems that the new lammps release causes problems with interactive lammps calculations.

**Comment by niklassiemer** [comment]
```
Input Notebook:  notebooks/gamma_surface_parallel_master.ipynb
Output Notebook: notebooks/gamma_surface_parallel_master-out.ipynb

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]Executing notebook with kernel: python3

Executing:   7%|▋         | 1/14 [00:01<00:16,  1.23s/cell]
Executing:  14%|█▍        | 2/14 [00:01<00:08,  1.43cell/s]
Executing:  21%|██▏       | 3/14 [00:03<00:12,  1.18s/cell]
Executing:  64%|██████▍   | 9/14 [00:03<00:01,  3.90cell/s]
Executing:  93%|█████████▎| 13/14 [00:04<00:00,  3.22cell/s]
Executing:  93%|█████████▎| 13/14 [00:06<00:00,  2.08cell/s]
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/bin/papermill", line 10, in <module>
    sys.exit(papermill())
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [7]":
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-7-555cceb77f6d> in <module>
     16         gs.input["n_mesh_x"] = 5
     17         gs.input["n_mesh_y"] = 19
---> 18         gs.run()
     19         ax.contourf(np.reshape(gs._output["energy"], (gs.input["n_mesh_x"],-1)))

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/generic/util.py in decorated(*args, **kwargs)
    211                         stacklevel=2
    212                     )
--> 213             return function(*args, **kwargs)
    214         return decorated
    215 

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
    660                 self._run_if_repair()
    661             elif status == "initialized":
--> 662                 self._run_if_new(debug=debug)
    663             elif status == "created":
    664                 self._run_if_created()

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/job/generic.py in _run_if_new(self, debug)
   1321         else:
   1322             self.save()
-> 1323             self.run()
   1324 
   1325     def _run_if_created(self):

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/generic/util.py in decorated(*args, **kwargs)
    211                         stacklevel=2
    212                     )
--> 213             return function(*args, **kwargs)
    214         return decorated
    215 

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
    662                 self._run_if_new(debug=debug)
    663             elif status == "created":
--> 664                 self._run_if_created()
    665             elif status == "submitted":
    666                 self._run_if_submitted()

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/job/generic.py in _run_if_created(self)
   1344             self.run_if_scheduler()
   1345         elif self.server.run_mode.interactive:
-> 1346             self.run_if_interactive()
   1347         elif self.server.run_mode.interactive_non_modal:
   1348             self.run_if_interactive_non_modal()

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/master/parallel.py in run_if_interactive(self)
    707             for parameter in self._job_generator.parameter_list:
    708                 self._job_generator.modify_job(job=self.ref_job, parameter=parameter)
--> 709                 self.ref_job.run()
    710             self.ref_job.interactive_close()
    711         else:

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/generic/util.py in decorated(*args, **kwargs)
    211                         stacklevel=2
    212                     )
--> 213             return function(*args, **kwargs)
    214         return decorated
    215 

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
    660                 self._run_if_repair()
    661             elif status == "initialized":
--> 662                 self._run_if_new(debug=debug)
    663             elif status == "created":
    664                 self._run_if_created()

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/job/generic.py in _run_if_new(self, debug)
   1321         else:
   1322             self.save()
-> 1323             self.run()
   1324 
   1325     def _run_if_created(self):

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/generic/util.py in decorated(*args, **kwargs)
    211                         stacklevel=2
    212                     )
--> 213             return function(*args, **kwargs)
    214         return decorated
    215 

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
    662                 self._run_if_new(debug=debug)
    663             elif status == "created":
--> 664                 self._run_if_created()
    665             elif status == "submitted":
    666                 self._run_if_submitted()

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/job/generic.py in _run_if_created(self)
   1344             self.run_if_scheduler()
   1345         elif self.server.run_mode.interactive:
-> 1346             self.run_if_interactive()
   1347         elif self.server.run_mode.interactive_non_modal:
   1348             self.run_if_interactive_non_modal()

~/work/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/lammps/interactive.py in run_if_interactive(self)
    323             super(LammpsInteractive, self).run_if_interactive()
    324             self.interactive_execute()
--> 325             self.interactive_collect()
    326 
    327     def validate_ready_to_run(self):

~/work/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/atomistics/job/interactive.py in interactive_collect(self)
    205         for k,v in self.interactive_output_functions.items():
    206             try:
--> 207                 value = v()
    208                 if value is not None:
    209                     self.interactive_cache[k].append(value)

~/work/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/lammps/interactive.py in interactive_forces_getter(self)
    137     def interactive_forces_getter(self):
    138         ff = np.reshape(
--> 139             np.array(self._interactive_library.gather_atoms("f", 1, 3)),
    140             (len(self.structure), 3),
    141         )

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/lammps/core.py in gather_atoms(self, name, dtype, count)
   1138       elif dtype == 1:
   1139         data = ((count*natoms)*c_double)()
-> 1140         self.lib.lammps_gather_atoms(self.lmp,name,type,count,data)
   1141       else:
   1142         return None

ArgumentError: argument 3: <class 'TypeError'>: wrong type
```
```
Input Notebook:  notebooks/test_pyiron_installation.ipynb
Output Notebook: notebooks/test_pyiron_installation-out.ipynb

Executing:   0%|          | 0/28 [00:00<?, ?cell/s]Executing notebook with kernel: python3

Executing:   4%|▎         | 1/28 [00:01<00:27,  1.03s/cell]
Executing:  18%|█▊        | 5/28 [00:04<00:20,  1.13cell/s]
Executing:  25%|██▌       | 7/28 [00:06<00:18,  1.13cell/s]
Executing:  39%|███▉      | 11/28 [00:06<00:07,  2.26cell/s]
Executing:  46%|████▋     | 13/28 [00:09<00:11,  1.32cell/s]
Executing:  54%|█████▎    | 15/28 [00:09<00:07,  1.77cell/s]
Executing:  64%|██████▍   | 18/28 [00:12<00:07,  1.32cell/s]
Executing:  68%|██████▊   | 19/28 [00:15<00:08,  1.01cell/s]
Executing:  75%|███████▌  | 21/28 [00:16<00:05,  1.23cell/s]
Executing:  75%|███████▌  | 21/28 [00:17<00:05,  1.22cell/s]
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/bin/papermill", line 10, in <module>
    sys.exit(papermill())
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [10]":
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-10-5721e4c3225e> in <module>
      5 lmp.potential = '2008--Hepburn-D-J--Fe-C--LAMMPS--ipr1'
      6 lmp.server.run_mode.interactive = True
----> 7 lmp.run()  # The job interactive was saved and received the ID: 1
      8 print(lmp.output.energy_tot)  # [-6.38884508]
      9 lmp.run()

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/generic/util.py in decorated(*args, **kwargs)
    211                         stacklevel=2
    212                     )
--> 213             return function(*args, **kwargs)
    214         return decorated
    215 

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
    660                 self._run_if_repair()
    661             elif status == "initialized":
--> 662                 self._run_if_new(debug=debug)
    663             elif status == "created":
    664                 self._run_if_created()

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/job/generic.py in _run_if_new(self, debug)
   1321         else:
   1322             self.save()
-> 1323             self.run()
   1324 
   1325     def _run_if_created(self):

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/generic/util.py in decorated(*args, **kwargs)
    211                         stacklevel=2
    212                     )
--> 213             return function(*args, **kwargs)
    214         return decorated
    215 

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
    662                 self._run_if_new(debug=debug)
    663             elif status == "created":
--> 664                 self._run_if_created()
    665             elif status == "submitted":
    666                 self._run_if_submitted()

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_base/job/generic.py in _run_if_created(self)
   1344             self.run_if_scheduler()
   1345         elif self.server.run_mode.interactive:
-> 1346             self.run_if_interactive()
   1347         elif self.server.run_mode.interactive_non_modal:
   1348             self.run_if_interactive_non_modal()

~/work/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/lammps/interactive.py in run_if_interactive(self)
    323             super(LammpsInteractive, self).run_if_interactive()
    324             self.interactive_execute()
--> 325             self.interactive_collect()
    326 
    327     def validate_ready_to_run(self):

~/work/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/atomistics/job/interactive.py in interactive_collect(self)
    205         for k,v in self.interactive_output_functions.items():
    206             try:
--> 207                 value = v()
    208                 if value is not None:
    209                     self.interactive_cache[k].append(value)

~/work/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/lammps/interactive.py in interactive_forces_getter(self)
    137     def interactive_forces_getter(self):
    138         ff = np.reshape(
--> 139             np.array(self._interactive_library.gather_atoms("f", 1, 3)),
    140             (len(self.structure), 3),
    141         )

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/lammps/core.py in gather_atoms(self, name, dtype, count)
   1138       elif dtype == 1:
   1139         data = ((count*natoms)*c_double)()
-> 1140         self.lib.lammps_gather_atoms(self.lmp,name,type,count,data)
   1141       else:
   1142         return None

ArgumentError: argument 3: <class 'TypeError'>: wrong type
```

**Comment by niklassiemer** [comment]
It works if I restrict `lammps < 2021.05.27` (#214). I suggest to merge that one as a quick fix for our CI and to get the new Lammps version supported as fast as possible!
