### ISSUE TITLE
ASE removed rotate_euler

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_atomistics#27]
Now the unit tests fail with: 

```
======================================================================
1871
ERROR: test_rotate_euler (atomistics.structure.test_atoms.TestAtoms)
1872
----------------------------------------------------------------------
1873
Traceback (most recent call last):
1874
  File "/home/runner/work/pyiron_atomistics/pyiron_atomistics/tests/atomistics/structure/test_atoms.py", line 453, in test_rotate_euler
1875
    basis.rotate_euler(phi=0.1 * np.pi)
1876
  File "/home/runner/work/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/atomistics/structure/atoms.py", line 2172, in __getattr__
1877
    return object.__getattribute__(self, item)
1878
AttributeError: 'Atoms' object has no attribute 'rotate_euler'
1879

1880
----------------------------------------------------------------------
1881
Ran 388 tests in 221.502s
```

**Comment by jan-janssen** [comment]
# Old 

```
>>> a1 = atoms.get_angle([0, 1, 2])
>>> atoms.set_angle([0, 1, 2], pi / 2)
>>> a2 = atoms.get_dihedral([0, 1, 2, 3])
>>> atoms.set_dihedral([0, 1, 2, 3], pi / 6)
>>> atoms.rotate_dihedral([0, 1, 2, 3], 10.5 * pi / 180)
>>> atoms.rotate('z', pi / 4)
>>> atoms.rotate_euler(phi=phi, theta=theta, psi=psi)
```

# New 

```
>>> a1 = atoms.get_angle(0, 1, 2) * pi / 180
>>> atoms.set_angle(0, 1, 2, angle=90)
>>> a2 = atoms.get_dihedral(0, 1, 2, 3) * pi / 180
>>> atoms.set_dihedral(0, 1, 2, 3, angle=30)
>>> atoms.rotate_dihedral(0, 1, 2, 3, angle=10.5)
>>> atoms.rotate(45, 'z')
>>> atoms.euler_rotate(phi=phi * 180 / pi,
...                    theta=theta * 180 / pi,
...                    psi=psi * 180 / pi)
```

Changed in 3.14.0 https://gitlab.com/ase/ase/-/blob/master/doc/releasenotes.rst
