### ISSUE TITLE
Unit tests on Windows run forever

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_atomistics#296]
And if I cancel them, they have e.g. the following error: (#289). Right now, we have more failed CI runs in our master than successful ones! Can someone relate the problems on Windows to some recent changes in the data base code? 
```
Traceback (most recent call last):
  File "C:\Miniconda\envs\test\lib\site-packages\pyiron_base\database\generic.py", line 578, in get_item_by_id
    return self.__get_items("id", int(item_id))[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Miniconda\envs\test\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Miniconda\envs\test\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Miniconda\envs\test\lib\site-packages\pyiron_base\job\generic.py", line 1663, in multiprocess_wrapper
    job_wrap = JobWrapper(
  File "C:\Miniconda\envs\test\lib\site-packages\pyiron_base\job\wrapper.py", line 50, in __init__
    self.job = pr.load(int(job_id))
  File "C:\Miniconda\envs\test\lib\site-packages\pyiron_base\project\generic.py", line 757, in load
    return self.load_from_jobpath(
  File "C:\Miniconda\envs\test\lib\site-packages\pyiron_base\project\generic.py", line 777, in load_from_jobpath
    job = jobpath(db=self.db, job_id=job_id, user=self.user)
  File "C:\Miniconda\envs\test\lib\site-packages\pyiron_base\job\path.py", line 468, in __init__
    db_entry = db.get_item_by_id(job_id)
  File "C:\Miniconda\envs\test\lib\site-packages\pyiron_base\database\generic.py", line 585, in get_item_by_id
    raise IndexError(
IndexError: ('Error when trying to find elements by given Job ID: ', IndexError('list index out of range'))
Coverage.py warning: Module pyiron_atomistics was never imported. (module-not-imported)
Coverage.py warning: No data was collected. (no-data-collected)
EProcess Process-2:
Traceback (most recent call last):
  File "C:\Miniconda\envs\test\lib\site-packages\pyiron_base\database\generic.py", line 578, in get_item_by_id
    return self.__get_items("id", int(item_id))[-1]
IndexError: list index out of range
```

**Comment by niklassiemer** [comment]
Looking through the last merged PRs it seems like PR #241 introduced the breaking of the CI for Windows.

**Comment by jan-janssen** [comment]
But why did it work when we disabled the `non_modal` tests?

**Comment by niklassiemer** [comment]
It was more related to change which branch is tested. In that branch I changed what is tested: branch itself instead of the merge see #302

**Comment by jan-janssen** [comment]
ok, thanks again for looking into this @niklassiemer
