### ISSUE TITLE
The thermal expansion notebook fails!

### ISSUE THREAD

**Issue by max-hassani** [pyiron/pyiron_atomistics#399]
By installing `pyiron_atomistics=0.2.28`, I noticed that github workflows for running `thermalexpansion` notebook fails with the following error:
```
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/bin/papermill", line 10, in <module>
    sys.exit(papermill())
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [19]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_5619/3405849516.py in <module>
      1 pr = Project('Al_potentials')
----> 2 pot_lst = pr['../first_steps/Al_T200K'].load_object().list_potentials()[:3]

AttributeError: 'Lammps' object has no attribute 'load_object'
```
**Here is the workflow failing: https://github.com/materialdigital/pyiron-workflow-thermalexpansion/pull/29**  
**I noticed a similar error in https://github.com/pyiron/pyiron/pull/1377**

**Comment by max-hassani** [comment]
From my tests, there is no need any more to use `load_object` method, and it suffices to use:
```
pot_lst = pr['../first_steps/Al_T200K'].list_potentials()[:3]
```
@pmrv , @sudarsan-surendralal, can you confirm this?

**Comment by sudarsan-surendralal** [comment]
> 
> 
> From my tests, there is no need any more to use `load_object` method, and it suffices to use:
> 
> ```
> pot_lst = pr['../first_steps/Al_T200K'].list_potentials()[:3]
> ```
> 
> @pmrv , @sudarsan-surendralal, can you confirm this?

Yes that's right. Better to change this then.

**Comment by max-hassani** [comment]
Thanks @sudarsan-surendralal. So I will close this issue :)
