### ISSUE TITLE
Unexpected failure of job submission

### ISSUE THREAD

**Issue by yuyuanjingxuan** [pyiron/pyiron_atomistics#639]
**Summary**

Dear all,

I submitted a serial of vasp jobs via pyiron this morning. All jobs were submitted successfully. About ten of them were running at noon. However, the rest crashed for unknown reasons. I did not modify the executable and change the local environment. 

I tried many ways such as inputting full path of executable to `job.excutables` and switching to different excutables. Unfortunately, none of them worked. 

Does anyone have an idea how it takes place and how to resolve it? Thank you very much! 

**pyiron Version and Platform**

pyiron.__version__ = '0.4.6'

**Expected Behavior**

The job is submitted successfully. 

**Actual Behavior**
The job crashed instantaneously. Its status in the job_table is "submitted", while it is not in the queue.
The error msg from `error.out` is shown below.
```bash
Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/cli/__main__.py", line 3, in <module>
    main()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/cli/__init__.py", line 63, in main
    args.cli(args)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/cli/wrapper.py", line 31, in main
    job_wrapper_function(
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/job/wrapper.py", line 171, in job_wrapper_function
    job.run()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/job/wrapper.py", line 124, in run
    self.job.run_static()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/job/generic.py", line 745, in run_static
    if self.executable.executable_path == "":
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/job/executable.py", line 195, in executable_path
    if self.storage.executable_path is not None:
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/generic/datacontainer.py", line 389, in __getattr__
    raise AttributeError(name) from None
AttributeError: executable_path
```
No vasp outputs were created.

**Steps to Reproduce**
Attached is an example of a simple vasp job
```python
from pyiron import Project

pr = Project('Test')
job = pr.create.job.Vasp(job_name='test')
job.structure = pr.create_ase_bulk('Pt')
job.set_kpoints([2,2,2])
job.calc_static(algorithm='Fast')
job.server.queue = 'cm'
job.server.cores = 10
job.executable.version = '5.4.4_mpi'
job.run()
```

**Comment by yuyuanjingxuan** [comment]
It is said that over 90% of computer problems could be solved by restarting your machine. I restarted my server. Up to now, none of the jobs has been crashed.

**Comment by pmrv** [comment]
Hey sorry for not replying earlier, the underlying issue was in the mean time fixed over [here](https://github.com/pyiron/pyiron_base/pull/763), but is not live on the cluster yet.  It should still work for you after the restarting, because the bug was only triggered when a newer version of pyiron tried to read things from an older one.  Since you resubmit the job is both written and read by the new version, which then does not trigger the bug anymore.  Let me know if this still pops up though.
