### ISSUE TITLE
Calphy errors

### ISSUE THREAD

**Issue by raynol-dsouza** [pyiron/pyiron_atomistics#702]
When trying to run the following snippet from the potentials workshop, 

```
job = pr.create.job.Calphy('test_job', delete_aborted_job=True)
job.structure = pr.create.structure.ase.bulk('Al', cubic=True, a=4.04539068).repeat(3)
job.potential = '2008--Mendelev-M-I--Al--LAMMPS--ipr1'
job.calc_free_energy(temperature=100, 
                     pressure=0, 
                     reference_phase="solid",
                     n_equilibration_steps=5000,
                     n_switching_steps=5000)
job.run()
```

I get the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/cmmc/ptmp/rads/ipykernel_2067/4091291924.py in <cell line: 13>()
     11                      n_equilibration_steps=5000,
     12                      n_switching_steps=5000)
---> 13 job.run()

~/pyiron_repos/pyiron_base/pyiron_base/utils/deprecate.py in decorated(*args, **kwargs)
    169                         stacklevel=2,
    170                     )
--> 171             return function(*args, **kwargs)
    172 
    173         return decorated

~/pyiron_repos/pyiron_base/pyiron_base/jobs/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
    727                 self._run_if_repair()
    728             elif status == "initialized":
--> 729                 self._run_if_new(debug=debug)
    730             elif status == "created":
    731                 self._run_if_created()

~/pyiron_repos/pyiron_base/pyiron_base/jobs/job/generic.py in _run_if_new(self, debug)
   1254             debug (bool): Debug Mode
   1255         """
-> 1256         run_job_with_status_initialized(job=self, debug=debug)
   1257 
   1258     def _run_if_created(self):

~/pyiron_repos/pyiron_base/pyiron_base/jobs/job/runfunction.py in run_job_with_status_initialized(job, debug)
     74     else:
     75         job.save()
---> 76         job.run()
     77 
     78 

~/pyiron_repos/pyiron_base/pyiron_base/utils/deprecate.py in decorated(*args, **kwargs)
    169                         stacklevel=2,
    170                     )
--> 171             return function(*args, **kwargs)
    172 
    173         return decorated

~/pyiron_repos/pyiron_base/pyiron_base/jobs/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
    729                 self._run_if_new(debug=debug)
    730             elif status == "created":
--> 731                 self._run_if_created()
    732             elif status == "submitted":
    733                 run_job_with_status_submitted(job=self)

~/pyiron_repos/pyiron_base/pyiron_base/jobs/job/generic.py in _run_if_created(self)
   1265             int: Queue ID - if the job was send to the queue
   1266         """
-> 1267         return run_job_with_status_created(job=self)
   1268 
   1269     def _run_if_repair(self):

~/pyiron_repos/pyiron_base/pyiron_base/jobs/job/runfunction.py in run_job_with_status_created(job)
     97         job.run_if_manually(_manually_print=False)
     98     elif job.server.run_mode.modal:
---> 99         job.run_static()
    100     elif (
    101         job.server.run_mode.non_modal

~/pyiron_repos/pyiron_atomistics/pyiron_atomistics/calphy/job.py in run_static(self)
    627             routine_alchemy(job)
    628         elif self.input.mode == "fe":
--> 629             routine_fe(job)
    630         elif self.input.mode == "ts":
    631             routine_ts(job)

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/calphy/routines.py in routine_fe(job)
    345     for i in range(job.calc.n_iterations):
    346         ts = time.time()
--> 347         job.run_integration(iteration=(i+1))
    348         te = (time.time() - ts)
    349         job.logger.info("Integration cycle %d finished in %f s"%(i+1, te))

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/calphy/solid.py in run_integration(self, iteration)
    378         #reapply
    379         for i in range(self.calc.n_elements):
--> 380             lmp.command("fix               ff%d g%d ti/spring %f %d %d function 2"%(i+1, i+1, self.k[i], 
    381                 self.calc._n_switching_steps, self.calc.n_equilibration_steps))
    382 

TypeError: must be real number, not NoneType
```

@srmnitc I believe this error comes from PR #697. I know I should be able to specify the spring constants as `job.input.spring_constants`, but I think setting it to `None` as default without the user knowing about it is quite troublesome.  Wouldn't it be better to specify it (to some other default than `None`) inside of `job.calc_free_energy()`? Also, there is another `spring_constant` key inside of `job.input.tolerance`. 

It would also be great to know if I need to specify a float/int or a list of spring constants.

**Comment by srmnitc** [comment]
@raynol-dsouza I did not catch this on the calphy side. I will look into this.

**Comment by raynol-dsouza** [comment]
Cool! I just ran into another error while submitting the job to the cluster:

```
Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/u/rads/pyiron_repos/pyiron_base/pyiron_base/cli/__main__.py", line 3, in <module>
    main()
  File "/u/rads/pyiron_repos/pyiron_base/pyiron_base/cli/__init__.py", line 63, in main
    args.cli(args)
  File "/u/rads/pyiron_repos/pyiron_base/pyiron_base/cli/wrapper.py", line 31, in main
    job_wrapper_function(
  File "/u/rads/pyiron_repos/pyiron_base/pyiron_base/jobs/job/wrapper.py", line 171, in job_wrapper_function
    job.run()
  File "/u/rads/pyiron_repos/pyiron_base/pyiron_base/jobs/job/wrapper.py", line 124, in run
    self.job.run_static()
  File "/u/rads/pyiron_repos/pyiron_atomistics/pyiron_atomistics/calphy/job.py", line 620, in run_static
    job = Solid(calculation=self.calc, simfolder=self.working_directory)
AttributeError: 'Calphy' object has no attribute 'calc'
```
I see the assignment of `self.calc = calc`, but `self.calc` hasn't been defined in the `__init__` of the `Calphy` class.

**Comment by srmnitc** [comment]
@raynol-dsouza maybe we need an update. Could you tell me the path of the Calphy class definition on the cluster please?

**Comment by raynol-dsouza** [comment]
I'm using a clone of the github repo for pyiron_atomistics and am on the most recent head.

**Comment by raynol-dsouza** [comment]
I think it needs a `validate_ready_to_run` method, to make sure that `write_structure` and `write_input` are called before the job is sent to the queue. I just saw in the output files, that `structure.inp` and `conf.data` have not been created.

**Comment by raynol-dsouza** [comment]
Ah, I see that the problem is that whatever is stored in `self.calc` is not saved to the hdf5 file, so when the job is submitted to the queue and it reloads using `from_hdf`, `self.calc` isn't loaded and that's why it complains.

**Comment by niklassiemer** [comment]
> @srmnitc I believe this error comes from PR #697. I know I should be able to specify the spring constants as `job.input.spring_constants`, but I think setting it to `None` as default without the user knowing about it is quite troublesome.  

For such things (if there is no easy to define default) we have the `validate_ready_to_run` method which should look
```python
def validate_ready_to_run(self):
    if job.input.spring_constants is None:
        raise ValueError("job.input.spring_constants has to be defined. ")
```
in this case.

**Comment by srmnitc** [comment]
> Ah, I see that the problem is that whatever is stored in `self.calc` is not saved to the hdf5 file, so when the job is submitted to the queue and it reloads using `from_hdf`, `self.calc` isn't loaded and that's why it complains.

Thanks for this pointer!

**Comment by srmnitc** [comment]
> job = pr.create.job.Calphy('test_job', delete_aborted_job=True)
> job.structure = pr.create.structure.ase.bulk('Al', cubic=True, a=4.04539068).repeat(3)
> job.potential = '2008--Mendelev-M-I--Al--LAMMPS--ipr1'
> job.calc_free_energy(temperature=100, 
>                      pressure=0, 
>                      reference_phase="solid",
>                      n_equilibration_steps=5000,
>                      n_switching_steps=5000)
> job.run()

The spring constants are automatically determined if you set it is None (which is the preferred way). This keyword is for overriding these settings. The error comes because the check to see if spring constant is None checks only for a single value while it can also be a list. I am fixing this on the calphy side https://github.com/ICAMS/calphy/issues/38

**Comment by srmnitc** [comment]
These issues are now fixed!
